package Exceptions;

public class exceptions1 {
	public static void possibleExceptions(int number) {
		int i = 100;
		// try catch;
		try {
			
		}catch(ArithmeticException ex) {
			System.out.println("Hey stupid u cant divide by 0");
			 
		}
		int result = i/number;
		System.out.println("Result of our computation is "+result);
	}
	
	public static void main(String[] args) {
		possibleExceptions(0);
	}

}
